language: node_js
node_js:
- node
deploy:
- provider: script
  script: bash scripts/deploy.sh
  on:
    branch: staging
- provider: script
  script: bash scripts/deploy.sh production
before_install:
- openssl aes-256-cbc -K $encrypted_9b00f5262c30_key -iv $encrypted_9b00f5262c30_iv
  -in travis_deploy.enc -out travis_deploy -d
