language: c
install: true
script: true
before_deploy:
- openssl aes-256-cbc -K $encrypted_9b00f5262c30_key -iv $encrypted_9b00f5262c30_iv
  -in travis_deploy.enc -out travis_deploy -d
- chmod 600 travis_deploy
- mv travis_deploy ~/.ssh/id_rsa
- apt-get install software-properties-common -y
- apt-add-repository ppa:ansible/ansible -y
- apt-get update
- apt-get install ansible -y
deploy:
- provider: script
  script: ansible-playbook -i deploy/inventory deploy/${TRAVIS_BRANCH}.yml
  on:
    branch:
      - staging